/*
 * Model Output Arena — manifest.
 * Loaded by compare.html via a <script> tag (works on file:// — no server needed).
 *
 * ADDING A MODEL: append a new entry to `models` below. Keep the same `outputs` keys
 * (the test ids). See PLAN.md for the full slug rules.
 */
window.ARENA = {
  tests: [
    { id: "01-car-parallax",      title: "01 · Animated Car — Parallax (vanilla canvas)" },
    { id: "02-plants-vs-zombies", title: "02 · Mini Plants vs Zombies (single HTML)" },
    { id: "03-threejs-thriller",  title: "03 · Three.js \"Thriller\" Dance Scene" },
    {
      provider: "local",
      provider_display: "Local (llama.cpp)",
      model: "nemotron-3.5-lightning-free",
      model_display: "Nemotron 3.5 Lightning Free",
      hosting: "local",
      weights: "open",
      path: "providers/local/nemotron-3.5-lightning-free",
      added: "2026-09-03",
      outputs: {
        "01-car-parallax":      "providers/local/nemotron-3.5-lightning-free/01-car-parallax/output.html",
        "02-plants-vs-zombies": "providers/local/nemotron-3.5-lightning-free/02-plants-vs-zombies/output.html",
        "03-threejs-thriller":  "providers/local/nemotron-3.5-lightning-free/03-threejs-thriller/output.html",
      },
    },
  ],
  models: [
    {
      provider: "z-ai",
      provider_display: "Z.AI",
      model: "glm-5-turbo",
      model_display: "GLM 5 Turbo",
      hosting: "api",
      weights: "closed",
      path: "providers/z-ai/glm-5-turbo",
      added: "2026-06-13",
      outputs: {
        "01-car-parallax":      "providers/z-ai/glm-5-turbo/01-car-parallax/output.html",
        "02-plants-vs-zombies": "providers/z-ai/glm-5-turbo/02-plants-vs-zombies/output.html",
        "03-threejs-thriller":  "providers/z-ai/glm-5-turbo/03-threejs-thriller/output.html",
      },
    },
    {
      provider: "anthropic",
      provider_display: "Anthropic",
      model: "claude-opus-4-8",
      model_display: "Claude Opus 4.8",
      hosting: "api",
      weights: "closed",
      path: "providers/anthropic/claude-opus-4-8",
      added: "2026-06-13",
      outputs: {
        "01-car-parallax":      "providers/anthropic/claude-opus-4-8/01-car-parallax/output.html",
        "02-plants-vs-zombies": "providers/anthropic/claude-opus-4-8/02-plants-vs-zombies/output.html",
        "03-threejs-thriller":  "providers/anthropic/claude-opus-4-8/03-threejs-thriller/output.html",
      },
    },
    {
      provider: "z-ai",
      provider_display: "Z.AI",
      model: "glm-5.2",
      model_display: "GLM 5.2",
      hosting: "api",
      weights: "open",
      path: "providers/z-ai/glm-5.2",
      added: "2026-06-13",
      outputs: {
        "01-car-parallax":      "providers/z-ai/glm-5.2/01-car-parallax/output.html",
        "02-plants-vs-zombies": "providers/z-ai/glm-5.2/02-plants-vs-zombies/output.html",
        "03-threejs-thriller":  "providers/z-ai/glm-5.2/03-threejs-thriller/output.html",
      },
    },
    {
      provider: "z-ai",
      provider_display: "Z.AI",
      model: "glm-5.1",
      model_display: "GLM 5.1",
      hosting: "api",
      weights: "open",
      path: "providers/z-ai/glm-5.1",
      added: "2026-06-13",
      outputs: {
        "01-car-parallax":      "providers/z-ai/glm-5.1/01-car-parallax/output.html",
        "02-plants-vs-zombies": "providers/z-ai/glm-5.1/02-plants-vs-zombies/output.html",
        "03-threejs-thriller":  "providers/z-ai/glm-5.1/03-threejs-thriller/output.html",
      },
    },
    {
      provider: "anthropic",
      provider_display: "Anthropic",
      model: "claude-haiku-4-5",
      model_display: "Claude Haiku 4.5",
      hosting: "api",
      weights: "closed",
      path: "providers/anthropic/claude-haiku-4-5",
      added: "2026-06-13",
      outputs: {
        "01-car-parallax":      "providers/anthropic/claude-haiku-4-5/01-car-parallax/output.html",
        "02-plants-vs-zombies": "providers/anthropic/claude-haiku-4-5/02-plants-vs-zombies/output.html",
        "03-threejs-thriller":  "providers/anthropic/claude-haiku-4-5/03-threejs-thriller/output.html",
      },
    },
    {
      provider: "openai",
      provider_display: "OpenAI",
      model: "gpt-5.5",
      model_display: "GPT-5.5",
      hosting: "api",
      weights: "closed",
      path: "providers/openai/gpt-5.5",
      added: "2026-06-13",
      outputs: {
        "01-car-parallax":      "providers/openai/gpt-5.5/01-car-parallax/output.html",
        "02-plants-vs-zombies": "providers/openai/gpt-5.5/02-plants-vs-zombies/output.html",
        "03-threejs-thriller":  "providers/openai/gpt-5.5/03-threejs-thriller/output.html",
      },
    },
    {
      provider: "openai",
      provider_display: "OpenAI",
      model: "gpt-5.5-native",
      model_display: "GPT-5.5 (Native Harness)",
      hosting: "api",
      weights: "closed",
      path: "providers/openai/gpt-5.5-native",
      added: "2026-06-13",
      outputs: {
        "01-car-parallax":      "providers/openai/gpt-5.5-native/01-car-parallax/output.html",
        "02-plants-vs-zombies": "providers/openai/gpt-5.5-native/02-plants-vs-zombies/output.html",
        "03-threejs-thriller":  "providers/openai/gpt-5.5-native/03-threejs-thriller/output.html",
      },
    },
    {
      provider: "qwen",
      provider_display: "Qwen",
      model: "qwen3.6-27b-heretic-v2",
      model_display: "Qwen 3.6 27B Heretic v2",
      hosting: "local",
      weights: "open",
      path: "providers/qwen/qwen3.6-27b-heretic-v2",
      added: "2026-06-13",
      outputs: {
        "01-car-parallax":      "providers/qwen/qwen3.6-27b-heretic-v2/01-car-parallax/output.html",
        "02-plants-vs-zombies": "providers/qwen/qwen3.6-27b-heretic-v2/02-plants-vs-zombies/output.html",
        "03-threejs-thriller":  "providers/qwen/qwen3.6-27b-heretic-v2/03-threejs-thriller/output.html",
      },
    },
    {
      provider: "google",
      provider_display: "Google",
      model: "gemma-4-26b-a4b-qat",
      model_display: "Gemma 4 26B A4B QAT",
      hosting: "local",
      weights: "open",
      path: "providers/google/gemma-4-26b-a4b-qat",
      added: "2026-06-13",
      outputs: {
        "01-car-parallax":      "providers/google/gemma-4-26b-a4b-qat/01-car-parallax/output.html",
        "02-plants-vs-zombies": "providers/google/gemma-4-26b-a4b-qat/02-plants-vs-zombies/output.html",
        "03-threejs-thriller":  "providers/google/gemma-4-26b-a4b-qat/03-threejs-thriller/output.html",
      },
    },
    {
      provider: "google",
      provider_display: "Google",
      model: "gemma-4-31b-qat",
      model_display: "Gemma 4 31B QAT",
      hosting: "local",
      weights: "open",
      path: "providers/google/gemma-4-31b-qat",
      added: "2026-06-13",
      outputs: {
        "01-car-parallax":      "providers/google/gemma-4-31b-qat/01-car-parallax/output.html",
        "02-plants-vs-zombies": "providers/google/gemma-4-31b-qat/02-plants-vs-zombies/output.html",
        "03-threejs-thriller":  "providers/google/gemma-4-31b-qat/03-threejs-thriller/output.html",
      },
    },
    {
      provider: "anthropic",
      provider_display: "Anthropic",
      model: "claude-sonnet-4-6",
      model_display: "Claude Sonnet 4.6",
      hosting: "api",
      weights: "closed",
      path: "providers/anthropic/claude-sonnet-4-6",
      added: "2026-06-13",
      outputs: {
        "01-car-parallax":      "providers/anthropic/claude-sonnet-4-6/01-car-parallax/output.html",
        "02-plants-vs-zombies": "providers/anthropic/claude-sonnet-4-6/02-plants-vs-zombies/output.html",
        "03-threejs-thriller":  "providers/anthropic/claude-sonnet-4-6/03-threejs-thriller/output.html",
      },
    },
    {
      provider: "z-ai",
      provider_display: "Z.AI",
      model: "glm-5.2-native",
      model_display: "GLM 5.2 (Native Harness)",
      hosting: "api",
      weights: "open",
      path: "providers/z-ai/glm-5.2-native",
      added: "2026-06-13",
      outputs: {
        "01-car-parallax":      "providers/z-ai/glm-5.2-native/01-car-parallax/output.html",
        "02-plants-vs-zombies": "providers/z-ai/glm-5.2-native/02-plants-vs-zombies/output.html",
        "03-threejs-thriller":  "providers/z-ai/glm-5.2-native/03-threejs-thriller/output.html",
      },
    },
    {
      provider: "google",
      provider_display: "Google",
      model: "gemini-3.1-pro",
      model_display: "Gemini 3.1 Pro (Native Harness)",
      hosting: "api",
      weights: "closed",
      path: "providers/google/gemini-3.1-pro",
      added: "2026-06-13",
      outputs: {
        "01-car-parallax":      "providers/google/gemini-3.1-pro/01-car-parallax/output.html",
        "02-plants-vs-zombies": "providers/google/gemini-3.1-pro/02-plants-vs-zombies/output.html",
        "03-threejs-thriller":  "providers/google/gemini-3.1-pro/03-threejs-thriller/output.html",
      },
    },
    {
      provider: "google",
      provider_display: "Google",
      model: "gemini-3.5-flash-native",
      model_display: "Gemini 3.5 Flash (Native Harness)",
      hosting: "api",
      weights: "closed",
      path: "providers/google/gemini-3.5-flash-native",
      added: "2026-06-13",
      outputs: {
        "01-car-parallax":      "providers/google/gemini-3.5-flash-native/01-car-parallax/output.html",
        "02-plants-vs-zombies": "providers/google/gemini-3.5-flash-native/02-plants-vs-zombies/output.html",
        "03-threejs-thriller":  "providers/google/gemini-3.5-flash-native/03-threejs-thriller/output.html",
      },
    },
    {
      provider: "anthropic",
      provider_display: "Anthropic",
      model: "claude-opus-4-8-native",
      model_display: "Claude Opus 4.8 (Native Harness)",
      hosting: "api",
      weights: "closed",
      path: "providers/anthropic/claude-opus-4-8-native",
      added: "2026-06-13",
      outputs: {
        "01-car-parallax":      "providers/anthropic/claude-opus-4-8-native/01-car-parallax/output.html",
        "02-plants-vs-zombies": "providers/anthropic/claude-opus-4-8-native/02-plants-vs-zombies/output.html",
        "03-threejs-thriller":  "providers/anthropic/claude-opus-4-8-native/03-threejs-thriller/output.html",
      },
    },
    {
      provider: "deepseek",
      provider_display: "DeepSeek",
      model: "deepseek-v4-pro",
      model_display: "DeepSeek V4 Pro",
      hosting: "api",
      weights: "closed",
      path: "providers/deepseek/deepseek-v4-pro",
      added: "2026-06-14",
      outputs: {
        "01-car-parallax":      "providers/deepseek/deepseek-v4-pro/01-car-parallax/output.html",
        "02-plants-vs-zombies": "providers/deepseek/deepseek-v4-pro/02-plants-vs-zombies/output.html",
        "03-threejs-thriller":  "providers/deepseek/deepseek-v4-pro/03-threejs-thriller/output.html",
      },
    },
    {
      provider: "deepseek",
      provider_display: "DeepSeek",
      model: "deepseek-v4-flash-0721",
      model_display: "DeepSeek V4 Flash 0721",
      hosting: "api",
      weights: "closed",
      path: "providers/deepseek/deepseek-v4-flash-0721",
      added: "2026-08-12",
      outputs: {
        "01-car-parallax":      "providers/deepseek/deepseek-v4-flash-0721/01-car-parallax/output.html",
        "02-plants-vs-zombies": "providers/deepseek/deepseek-v4-flash-0721/02-plants-vs-zombies/output.html",
        "03-threejs-thriller":  "providers/deepseek/deepseek-v4-flash-0721/03-threejs-thriller/output.html",
      },
    },
    {
      provider: "minimax",
      provider_display: "MiniMax",
      model: "minimax-m3",
      model_display: "MiniMax-M3",
      hosting: "api",
      weights: "closed",
      path: "providers/minimax/minimax-m3",
      added: "2026-06-14",
      outputs: {
        "01-car-parallax":      "providers/minimax/minimax-m3/01-car-parallax/output.html",
        "02-plants-vs-zombies": "providers/minimax/minimax-m3/02-plants-vs-zombies/output.html",
        "03-threejs-thriller":  "providers/minimax/minimax-m3/03-threejs-thriller/output.html",
      },
    },
    {
      provider: "minimax",
      provider_display: "MiniMax",
      model: "minimax-m3-native",
      model_display: "MiniMax-M3 (Native Harness)",
      hosting: "api",
      weights: "closed",
      path: "providers/minimax/minimax-m3-native",
      added: "2026-06-14",
      outputs: {
        "01-car-parallax":      "providers/minimax/minimax-m3-native/01-car-parallax/output.html",
        "02-plants-vs-zombies": "providers/minimax/minimax-m3-native/02-plants-vs-zombies/output.html",
        "03-threejs-thriller":  "providers/minimax/minimax-m3-native/03-threejs-thriller/output.html",
      },
    },
    {
      provider: "local",
      provider_display: "Local (llama.cpp)",
      model: "ornith-1.0-35b-uncensored",
      model_display: "Ornith 1.0 35B Uncensored",
      hosting: "local",
      weights: "open",
      path: "providers/local/ornith-1.0-35b-uncensored",
      added: "2026-07-01",
      outputs: {
        "01-car-parallax":      "providers/local/ornith-1.0-35b-uncensored/01-car-parallax/output.html",
        "02-plants-vs-zombies": "providers/local/ornith-1.0-35b-uncensored/02-plants-vs-zombies/output.html",
        "03-threejs-thriller":  "providers/local/ornith-1.0-35b-uncensored/03-threejs-thriller/output.html",
      },
    },
    {
      provider: "local",
      provider_display: "Local (llama.cpp)",
      model: "qwopus3.6-27b-coder-mtp",
      model_display: "QwOpus 3.6 27B Coder MTP",
      hosting: "local",
      weights: "open",
      path: "providers/local/qwopus3.6-27b-coder-mtp",
      added: "2026-07-02",
      outputs: {
        "01-car-parallax":      "providers/local/qwopus3.6-27b-coder-mtp/01-car-parallax/output.html",
        "02-plants-vs-zombies": "providers/local/qwopus3.6-27b-coder-mtp/02-plants-vs-zombies/output.html",
        "03-threejs-thriller":  "providers/local/qwopus3.6-27b-coder-mtp/03-threejs-thriller/output.html",
      },
    },
    {
      provider: "local",
      provider_display: "Local (llama.cpp)",
      model: "qwen3.6-27b-uncensored-heretic-v2-native-mtp-preserved",
      model_display: "Qwen 3.6 27B Uncensored Heretic v2 Native MTP",
      hosting: "local",
      weights: "open",
      path: "providers/local/qwen3.6-27b-uncensored-heretic-v2-native-mtp-preserved",
      added: "2026-07-02",
      outputs: {
        "01-car-parallax":      "providers/local/qwen3.6-27b-uncensored-heretic-v2-native-mtp-preserved/01-car-parallax/output.html",
        "02-plants-vs-zombies": "providers/local/qwen3.6-27b-uncensored-heretic-v2-native-mtp-preserved/02-plants-vs-zombies/output.html",
        "03-threejs-thriller":  "providers/local/qwen3.6-27b-uncensored-heretic-v2-native-mtp-preserved/03-threejs-thriller/output.html",
      },
    },
    {
      provider: "anthropic",
      provider_display: "Anthropic",
      model: "claude-fable-5",
      model_display: "Claude Fable 5",
      hosting: "api",
      weights: "closed",
      path: "providers/anthropic/claude-fable-5",
      added: "2026-07-02",
      outputs: {
        "01-car-parallax":      "providers/anthropic/claude-fable-5/01-car-parallax/output.html",
        "02-plants-vs-zombies": "providers/anthropic/claude-fable-5/02-plants-vs-zombies/output.html",
        "03-threejs-thriller":  "providers/anthropic/claude-fable-5/03-threejs-thriller/output.html",
      },
    },
    {
      provider: "anthropic",
      provider_display: "Anthropic",
      model: "claude-fable-5.1",
      model_display: "Claude Fable 5.1",
      hosting: "api",
      weights: "closed",
      path: "providers/anthropic/claude-fable-5.1",
      added: "2026-09-03",
      outputs: {
        "01-car-parallax":      "providers/anthropic/claude-fable-5.1/01-car-parallax/output.html",
        "02-plants-vs-zombies": "providers/anthropic/claude-fable-5.1/02-plants-vs-zombies/output.html",
        "03-threejs-thriller":  "providers/anthropic/claude-fable-5.1/03-threejs-thriller/output.html",
      },
    },
    {
      provider: "local",
      provider_display: "Local (llama.cpp)",
      model: "brian6145-qwen3.6-27b-claude-opus-sonnet-distilledv2-mtp",
      model_display: "Qwen 3.6 27B Claude Opus/Sonnet Distilled v2 MTP (brian6145)",
      hosting: "local",
      weights: "open",
      path: "providers/local/brian6145-qwen3.6-27b-claude-opus-sonnet-distilledv2-mtp",
      added: "2026-07-02",
      outputs: {
        "01-car-parallax":      "providers/local/brian6145-qwen3.6-27b-claude-opus-sonnet-distilledv2-mtp/01-car-parallax/output.html",
        "02-plants-vs-zombies": "providers/local/brian6145-qwen3.6-27b-claude-opus-sonnet-distilledv2-mtp/02-plants-vs-zombies/output.html",
        "03-threejs-thriller":  "providers/local/brian6145-qwen3.6-27b-claude-opus-sonnet-distilledv2-mtp/03-threejs-thriller/output.html",
      },
    },
    {
      provider: "local",
      provider_display: "Local (llama.cpp)",
      model: "agents-a1-0",
      model_display: "Agents A1 0",
      hosting: "local",
      weights: "open",
      path: "providers/local/agents-a1-0",
      added: "2026-07-02",
      outputs: {
        "01-car-parallax":      "providers/local/agents-a1-0/01-car-parallax/output.html",
        "02-plants-vs-zombies": "providers/local/agents-a1-0/02-plants-vs-zombies/output.html",
        "03-threejs-thriller":  "providers/local/agents-a1-0/03-threejs-thriller/output.html",
      },
    },
    {
      provider: "openai",
      provider_display: "OpenAI",
      model: "gpt-5.6-sol",
      model_display: "GPT-5.6 Sol",
      hosting: "api",
      weights: "closed",
      path: "providers/openai/gpt-5.6-sol",
      added: "2026-07-10",
      outputs: {
        "01-car-parallax":      "providers/openai/gpt-5.6-sol/01-car-parallax/output.html",
        "02-plants-vs-zombies": "providers/openai/gpt-5.6-sol/02-plants-vs-zombies/output.html",
        "03-threejs-thriller":  "providers/openai/gpt-5.6-sol/03-threejs-thriller/output.html",
      },
    },
    {
      provider: "openai",
      provider_display: "OpenAI",
      model: "gpt-5.6-terra",
      model_display: "GPT-5.6 Terra",
      hosting: "api",
      weights: "closed",
      path: "providers/openai/gpt-5.6-terra",
      added: "2026-07-10",
      outputs: {
        "01-car-parallax":      "providers/openai/gpt-5.6-terra/01-car-parallax/output.html",
        "02-plants-vs-zombies": "providers/openai/gpt-5.6-terra/02-plants-vs-zombies/output.html",
        "03-threejs-thriller":  "providers/openai/gpt-5.6-terra/03-threejs-thriller/output.html",
      },
    },
    {
      provider: "openai",
      provider_display: "OpenAI",
      model: "gpt-5.6-luna",
      model_display: "GPT-5.6 Luna",
      hosting: "api",
      weights: "closed",
      path: "providers/openai/gpt-5.6-luna",
      added: "2026-07-10",
      outputs: {
        "01-car-parallax":      "providers/openai/gpt-5.6-luna/01-car-parallax/output.html",
        "02-plants-vs-zombies": "providers/openai/gpt-5.6-luna/02-plants-vs-zombies/output.html",
        "03-threejs-thriller":  "providers/openai/gpt-5.6-luna/03-threejs-thriller/output.html",
      },
    },
    {
      provider: "local",
      provider_display: "Local (llama.cpp)",
      model: "laguna-s-2.1 i3XSS",
      model_display: "Laguna S 2.1 i3XSS",
      hosting: "local",
      weights: "open",
      path: "providers/local/laguna-s-2.1",
      added: "2026-07-23",
      outputs: {
        "01-car-parallax":      "providers/local/laguna-s-2.1/01-car-parallax/output.html",
        "02-plants-vs-zombies": "providers/local/laguna-s-2.1/02-plants-vs-zombies/output.html",
        "03-threejs-thriller":  "providers/local/laguna-s-2.1/03-threejs-thriller/output.html",
      },
    },
    {
      provider: "anthropic",
      provider_display: "Anthropic",
      model: "claude-opus-5",
      model_display: "Claude Opus 5",
      hosting: "api",
      weights: "closed",
      path: "providers/anthropic/claude-opus-5",
      added: "2026-07-24",
      outputs: {
        "01-car-parallax":      "providers/anthropic/claude-opus-5/01-car-parallax/output.html",
        "02-plants-vs-zombies": "providers/anthropic/claude-opus-5/02-plants-vs-zombies/output.html",
        "03-threejs-thriller":  "providers/anthropic/claude-opus-5/03-threejs-thriller/output.html",
      },
    },
    {
      provider: "google",
      provider_display: "Google",
      model: "gemini-3.6-flash-high",
      model_display: "Gemini 3.6 Flash High (Antigravity Harness)",
      hosting: "api",
      weights: "closed",
      path: "providers/google/gemini-3.6-flash-high",
      added: "2026-07-24",
      outputs: {
        "01-car-parallax":      "providers/google/gemini-3.6-flash-high/01-car-parallax/output.html",
        "02-plants-vs-zombies": "providers/google/gemini-3.6-flash-high/02-plants-vs-zombies/output.html",
        "03-threejs-thriller":  "providers/google/gemini-3.6-flash-high/03-threejs-thriller/output.html",
      },
    },
    {
      provider: "qwen",
      provider_display: "Qwen",
      model: "qwen-3.8-max-preview",
      model_display: "Qwen 3.8 Max Preview",
      hosting: "api",
      weights: "closed",
      path: "providers/qwen/qwen-3.8-max-preview",
      added: "2026-07-29",
      outputs: {
        "01-car-parallax":      "providers/qwen/qwen-3.8-max-preview/01-car-parallax/output.html",
        "02-plants-vs-zombies": "providers/qwen/qwen-3.8-max-preview/02-plants-vs-zombies/output.html",
        "03-threejs-thriller":  "providers/qwen/qwen-3.8-max-preview/03-threejs-thriller/output.html",
      },
    },
    {
      provider: "local",
      provider_display: "Local (llama.cpp)",
      model: "qwen3.6-27b-a3b-uncensored",
      model_display: "Qwen 3.6 27B A3B Uncensored",
      hosting: "local",
      weights: "open",
      path: "providers/local/qwen3.6-27b-a3b-uncensored",
      added: "2025-08-06",
      outputs: {
        "01-car-parallax":      "providers/local/qwen3.6-27b-a3b-uncensored/01-car-parallax/output.html",
        "02-plants-vs-zombies": "providers/local/qwen3.6-27b-a3b-uncensored/02-plants-vs-zombies/output.html",
        "03-threejs-thriller":  "providers/local/qwen3.6-27b-a3b-uncensored/03-threejs-thriller/output.html",
      },
    },
    {
      provider: "local",
      provider_display: "Local (llama.cpp)",
      model: "qwen3.6-27b-fable-fusion-711",
      model_display: "Qwen 3.6 27B Fable Fusion 711",
      hosting: "local",
      weights: "open",
      path: "providers/local/qwen3.6-27b-fable-fusion-711",
      added: "2026-08-08",
      outputs: {
        "01-car-parallax":      "providers/local/qwen3.6-27b-fable-fusion-711/01-car-parallax/output.html",
        "02-plants-vs-zombies": "providers/local/qwen3.6-27b-fable-fusion-711/02-plants-vs-zombies/output.html",
        "03-threejs-thriller":  "providers/local/qwen3.6-27b-fable-fusion-711/03-threejs-thriller/output.html",
      },
    },
    {
      provider: "local",
      provider_display: "Local (llama.cpp)",
      model: "muse-glimmer-30b",
      model_display: "Muse Glimmer 30B",
      hosting: "local",
      weights: "open",
      path: "providers/local/muse-glimmer-30b",
      added: "2026-06-13",
      outputs: {
        "01-car-parallax":      "providers/local/muse-glimmer-30b/01-car-parallax/output.html",
        "02-plants-vs-zombies": "providers/local/muse-glimmer-30b/02-plants-vs-zombies/output.html",
        "03-threejs-thriller":  "providers/local/muse-glimmer-30b/03-threejs-thriller/output.html",
      },
    },
    {
      provider: "google",
      provider_display: "Google",
      model: "gemini-3.7-flash-high",
      model_display: "Gemini 3.7 Flash High (Antigravity Harness)",
      hosting: "api",
      weights: "closed",
      path: "providers/google/gemini-3.7-flash-high",
      added: "2026-08-14",
      outputs: {
        "01-car-parallax":      "providers/google/gemini-3.7-flash-high/01-car-parallax/output.html",
        "02-plants-vs-zombies": "providers/google/gemini-3.7-flash-high/02-plants-vs-zombies/output.html",
        "03-threejs-thriller":  "providers/google/gemini-3.7-flash-high/03-threejs-thriller/output.html",
      },
    },
    {
      provider: "local",
      provider_display: "Local (llama.cpp)",
      model: "dirk-qwen3.8-27b",
      model_display: "Dirk Qwen 3.8 27B",
      hosting: "local",
      weights: "open",
      path: "providers/local/dirk-qwen3.8-27b",
      added: "2026-08-14",
      outputs: {
        "01-car-parallax":      "providers/local/dirk-qwen3.8-27b/01-car-parallax/output.html",
        "02-plants-vs-zombies": "providers/local/dirk-qwen3.8-27b/02-plants-vs-zombies/output.html",
        "03-threejs-thriller":  "providers/local/dirk-qwen3.8-27b/03-threejs-thriller/output.html",
      },
    },
    {
      provider: "local",
      provider_display: "Local (llama.cpp)",
      model: "qwen3.8-27b",
      model_display: "Qwen 3.8 27B",
      hosting: "local",
      weights: "open",
      path: "providers/local/qwen3.8-27b",
      added: "2026-08-14",
      outputs: {
        "01-car-parallax":      "providers/local/qwen3.8-27b/01-car-parallax/output.html",
        "02-plants-vs-zombies": "providers/local/qwen3.8-27b/02-plants-vs-zombies/output.html",
        "03-threejs-thriller":  "providers/local/qwen3.8-27b/03-threejs-thriller/output.html",
      },
    },
    {
      provider: "local",
      provider_display: "Local (llama.cpp)",
      model: "qwen3.8-27b-heretic",
      model_display: "Qwen 3.8 27B Heretic",
      hosting: "local",
      weights: "open",
      path: "providers/local/qwen3.8-27b-heretic",
      added: "2026-08-15",
      outputs: {
        "01-car-parallax":      "providers/local/qwen3.8-27b-heretic/01-car-parallax/output.html",
        "02-plants-vs-zombies": "providers/local/qwen3.8-27b-heretic/02-plants-vs-zombies/output.html",
        "03-threejs-thriller":  "providers/local/qwen3.8-27b-heretic/03-threejs-thriller/output.html",
      },
    },
    {
      provider: "local",
      provider_display: "Local (llama.cpp)",
      model: "qwen3.8-27b-native",
      model_display: "Qwen 3.8 27B (Native Harness)",
      hosting: "local",
      weights: "open",
      path: "providers/local/qwen3.8-27b-native",
      added: "2026-08-18",
      outputs: {
        "01-car-parallax":      "providers/local/qwen3.8-27b-native/01-car-parallax/output.html",
        "02-plants-vs-zombies": "providers/local/qwen3.8-27b-native/02-plants-vs-zombies/output.html",
        "03-threejs-thriller":  "providers/local/qwen3.8-27b-native/03-threejs-thriller/output.html",
      },
    },
    {
      provider: "local",
      provider_display: "Local (llama.cpp)",
      model: "ornith-1.5-35b-a3b",
      model_display: "Ornith 1.5 35B A3B",
      hosting: "local",
      weights: "open",
      path: "providers/local/ornith-1.5-35b-a3b",
      added: "2026-08-08",
      outputs: {
        "01-car-parallax":      "providers/local/ornith-1.5-35b-a3b/01-car-parallax/output.html",
        "02-plants-vs-zombies": "providers/local/ornith-1.5-35b-a3b/02-plants-vs-zombies/output.html",
        "03-threejs-thriller":  "providers/local/ornith-1.5-35b-a3b/03-threejs-thriller/output.html",
      },
    },
    {
      provider: "xai",
      provider_display: "xAI",
      model: "grok-4.6",
      model_display: "Grok 4.6",
      hosting: "api",
      weights: "closed",
      path: "providers/xai/grok-4.6",
      added: "2026-08-20",
      outputs: {
        "01-car-parallax":      "providers/xai/grok-4.6/01-car-parallax/output.html",
        "02-plants-vs-zombies": "providers/xai/grok-4.6/02-plants-vs-zombies/output.html",
        "03-threejs-thriller":  "providers/xai/grok-4.6/03-threejs-thriller/output.html",
      },
    },
    {
      provider: "local",
      provider_display: "Local (llama.cpp)",
      model: "qwen3.8-27b-heretic-native",
      model_display: "Qwen 3.8 27B Heretic (Native Harness)",
      hosting: "local",
      weights: "open",
      path: "providers/local/qwen3.8-27b-heretic-native",
      added: "2026-08-20",
      outputs: {
        "01-car-parallax":      "providers/local/qwen3.8-27b-heretic-native/01-car-parallax/output.html",
        "02-plants-vs-zombies": "providers/local/qwen3.8-27b-heretic-native/02-plants-vs-zombies/output.html",
        "03-threejs-thriller":  "providers/local/qwen3.8-27b-heretic-native/03-threejs-thriller/output.html",
      },
    },
    {
      provider: "undisclosed",
      provider_display: "Undisclosed",
      model: "ox-alpha",
      model_display: "Ox Alpha",
      hosting: "api",
      weights: "closed",
      path: "providers/undisclosed/ox-alpha",
      added: "2026-08-22",
      outputs: {
        "01-car-parallax":      "providers/undisclosed/ox-alpha/01-car-parallax/output.html",
        "02-plants-vs-zombies": "providers/undisclosed/ox-alpha/02-plants-vs-zombies/output.html",
        "03-threejs-thriller":  "providers/undisclosed/ox-alpha/03-threejs-thriller/output.html",
      },
    },
    {
      provider: "local",
      provider_display: "Local (llama.cpp)",
      model: "qwen3.8-flash-next-ud-iq3-xxs",
      model_display: "Qwen3.8 Flash Next UD-IQ3_XXS",
      hosting: "local",
      weights: "open",
      path: "providers/local/qwen3.8-flash-next-ud-iq3-xxs",
      added: "2026-08-27",
      outputs: {
        "01-car-parallax":      "providers/local/qwen3.8-flash-next-ud-iq3-xxs/01-car-parallax/output.html",
        "02-plants-vs-zombies": "providers/local/qwen3.8-flash-next-ud-iq3-xxs/02-plants-vs-zombies/output.html",
        "03-threejs-thriller":  "providers/local/qwen3.8-flash-next-ud-iq3-xxs/03-threejs-thriller/output.html",
      },
    },
    {
      provider: "local",
      provider_display: "Local (llama.cpp)",
      model: "qwen3.8-27b-hauhaucs-q8-k-p",
      model_display: "Qwen3.8-27B HauhauCS Q8_K_P",
      hosting: "local",
      weights: "open",
      path: "providers/local/qwen3.8-27b-hauhaucs-q8-k-p",
      added: "2026-08-27",
      outputs: {
        "01-car-parallax":      "providers/local/qwen3.8-27b-hauhaucs-q8-k-p/01-car-parallax/output.html",
        "02-plants-vs-zombies": "providers/local/qwen3.8-27b-hauhaucs-q8-k-p/02-plants-vs-zombies/output.html",
        "03-threejs-thriller":  "providers/local/qwen3.8-27b-hauhaucs-q8-k-p/03-threejs-thriller/output.html",
      },
    },
    {
      provider: "local",
      provider_display: "Local (llama.cpp)",
      model: "tiel-coder-35b-a3b-gguf-mtp-q8",
      model_display: "Tiel-Coder 35B A3B GGUF MTP q8",
      hosting: "local",
      weights: "open",
      path: "providers/local/tiel-coder-35b-a3b-gguf-mtp-q8",
      added: "2026-08-30",
      outputs: {
        "01-car-parallax":      "providers/local/tiel-coder-35b-a3b-gguf-mtp-q8/01-car-parallax/output.html",
        "02-plants-vs-zombies": "providers/local/tiel-coder-35b-a3b-gguf-mtp-q8/02-plants-vs-zombies/output.html",
        "03-threejs-thriller":  "providers/local/tiel-coder-35b-a3b-gguf-mtp-q8/03-threejs-thriller/output.html",
      },
    },
    {
      provider: "local",
      provider_display: "Local (llama.cpp)",
      model: "qwen3.8-flash-next-uncensored-iq4xs-ngq4",
      model_display: "Qwen3.8 Flash Next Uncensored IQ4XS_NGQ4",
      hosting: "local",
      weights: "open",
      path: "providers/local/qwen3.8-flash-next-uncensored-iq4xs-ngq4",
      added: "2026-09-01",
      outputs: {
        "01-car-parallax":      "providers/local/qwen3.8-flash-next-uncensored-iq4xs-ngq4/01-car-parallax/output.html",
        "02-plants-vs-zombies": "providers/local/qwen3.8-flash-next-uncensored-iq4xs-ngq4/02-plants-vs-zombies/output.html",
        "03-threejs-thriller":  "providers/local/qwen3.8-flash-next-uncensored-iq4xs-ngq4/03-threejs-thriller/output.html",
      },
    },
    {
      provider: "local",
      provider_display: "Local (llama.cpp)",
      model: "nemotron-3.5-lightning-free",
      model_display: "Nemotron 3.5 Lightning Free",
      hosting: "local",
      weights: "open",
      path: "providers/local/nemotron-3.5-lightning-free",
      added: "2026-09-03",
      outputs: {
        "01-car-parallax":      "providers/local/nemotron-3.5-lightning-free/01-car-parallax/output.html",
        "02-plants-vs-zombies": "providers/local/nemotron-3.5-lightning-free/02-plants-vs-zombies/output.html",
        "03-threejs-thriller":  "providers/local/nemotron-3.5-lightning-free/03-threejs-thriller/output.html",
      },
    },
    {
      provider: "local",
      provider_display: "Local (llama.cpp)",
      model: "qwen3.8-27b-uncensored-hauhaucs-aggressive-q8-k-p",
      model_display: "Qwen3.8-27B Uncensored HauhauCS Aggressive Q8_K_P",
      hosting: "local",
      weights: "open",
      path: "providers/local/qwen3.8-27b-uncensored-hauhaucs-aggressive-q8-k-p",
      added: "2026-09-04",
      outputs: {
        "01-car-parallax":      "providers/local/qwen3.8-27b-uncensored-hauhaucs-aggressive-q8-k-p/01-car-parallax/output.html",
        "02-plants-vs-zombies": "providers/local/qwen3.8-27b-uncensored-hauhaucs-aggressive-q8-k-p/02-plants-vs-zombies/output.html",
        "03-threejs-thriller":  "providers/local/qwen3.8-27b-uncensored-hauhaucs-aggressive-q8-k-p/03-threejs-thriller/output.html",
      },
    },
    {
      provider: "openai",
      provider_display: "OpenAI",
      model: "gpt-6",
      model_display: "GPT-6",
      hosting: "api",
      weights: "closed",
      path: "providers/openai/gpt-6",
      added: "2026-09-05",
      outputs: {
        "01-car-parallax": "providers/openai/gpt-6/01-car-parallax/output.html",
        "02-plants-vs-zombies": "providers/openai/gpt-6/02-plants-vs-zombies/output.html",
        "03-threejs-thriller": "providers/openai/gpt-6/03-threejs-thriller/output.html",
      },
    },
  ]
};

