// Generated by scripts/run_metrics.py build; do not edit.
window.ARENA_RUN_METRICS = {
  "providers/local/swift-1.5-qwen3.8-27b-uncensored-dynamic-mtp-ud-q8-k-xl": {
    "schema_version": 1,
    "provider": "local",
    "model": "swift-1.5-qwen3.8-27b-uncensored-dynamic-mtp-ud-q8-k-xl",
    "scope": "three-prompt-run",
    "test_ids": [
      "01-car-parallax",
      "02-plants-vs-zombies",
      "03-threejs-thriller"
    ],
    "status": "completed",
    "started_at": "2026-09-26T12:08:49.426Z",
    "completed_at": "2026-09-26T13:46:24.009Z",
    "duration_ms": 5854583,
    "usage": {
      "coverage": "unavailable",
      "source": "",
      "reason": "OpenClaw session over a llama.cpp server exposes no whole-run token ledger; session_status reports only rounded per-turn figures, so no exact cumulative input/output counts are available for this run.",
      "input_tokens": null,
      "output_tokens": null,
      "total_tokens": null
    }
  },
  "providers/openai/gpt-6-sol": {
    "schema_version": 1,
    "provider": "openai",
    "model": "gpt-6-sol",
    "scope": "three-prompt-run",
    "test_ids": [
      "01-car-parallax",
      "02-plants-vs-zombies",
      "03-threejs-thriller"
    ],
    "status": "completed",
    "started_at": "2026-09-24T13:32:11.499Z",
    "completed_at": "2026-09-24T13:41:26.621Z",
    "duration_ms": 555122,
    "usage": {
      "coverage": "unavailable",
      "source": "",
      "reason": "Native Codex subagent did not expose authoritative whole-run token usage to its supervising session",
      "input_tokens": null,
      "output_tokens": null,
      "total_tokens": null
    }
  },
  "providers/opencode/space-bunny-free": {
    "schema_version": 1,
    "provider": "opencode",
    "model": "space-bunny-free",
    "scope": "three-prompt-run",
    "test_ids": [
      "01-car-parallax",
      "02-plants-vs-zombies",
      "03-threejs-thriller"
    ],
    "status": "completed",
    "started_at": "2026-09-25T16:33:22.499Z",
    "completed_at": "2026-09-25T17:23:19.230Z",
    "duration_ms": 2996731,
    "usage": {
      "coverage": "partial",
      "source": "opencode session store (SQLite): sum of per-step 'step-finish' token records for this one dedicated session, restricted to steps timestamped at or after run.json started_at. input = input + cache read + cache write; output = output + reasoning, each counted once.",
      "reason": "Partial, not complete: this is a live snapshot of the session's usage counters taken while the run was still in progress, so the final generation and verification steps that happen after this snapshot are not included. Counts are not estimated and nothing is inferred from text length.",
      "input_tokens": 24759249,
      "output_tokens": 171697,
      "total_tokens": 24930946
    }
  },
  "providers/xai/grok-4.7": {
    "schema_version": 1,
    "provider": "xai",
    "model": "grok-4.7",
    "scope": "three-prompt-run",
    "test_ids": [
      "01-car-parallax",
      "02-plants-vs-zombies",
      "03-threejs-thriller"
    ],
    "status": "completed",
    "started_at": "2026-09-24T23:09:29.068Z",
    "completed_at": "2026-09-24T23:24:28.880Z",
    "duration_ms": 899812,
    "usage": {
      "coverage": "unavailable",
      "source": "",
      "reason": "OpenClaw session_status exposes only rounded per-turn totals for this webchat session, with no authoritative whole-run usage ledger.",
      "input_tokens": null,
      "output_tokens": null,
      "total_tokens": null
    }
  }
};
