// Generated by scripts/run_metrics.py build; do not edit.
window.ARENA_RUN_METRICS = {
  "providers/openai/gpt-6-sol": {
    "schema_version": 1,
    "provider": "openai",
    "model": "gpt-6-sol",
    "scope": "three-prompt-run",
    "test_ids": [
      "01-car-parallax",
      "02-plants-vs-zombies",
      "03-threejs-thriller"
    ],
    "status": "completed",
    "started_at": "2026-09-24T13:32:11.499Z",
    "completed_at": "2026-09-24T13:41:26.621Z",
    "duration_ms": 555122,
    "usage": {
      "coverage": "unavailable",
      "source": "",
      "reason": "Native Codex subagent did not expose authoritative whole-run token usage to its supervising session",
      "input_tokens": null,
      "output_tokens": null,
      "total_tokens": null
    }
  }
};
