import hashlib
import importlib.util
import json
from pathlib import Path
import subprocess
import sys
import tempfile
import unittest
from unittest.mock import patch

REPO = Path(__file__).resolve().parents[1]
spec = importlib.util.spec_from_file_location("run_metrics", REPO / "scripts/run_metrics.py")
metrics = importlib.util.module_from_spec(spec)
spec.loader.exec_module(metrics)


def usage(**changes):
    result = dict(coverage="complete", source="test fixture counters, not a benchmark",
                  reason="", input_tokens=120, output_tokens=80, total_tokens=200)
    result.update(changes)
    return result


class RunMetricsTests(unittest.TestCase):
    def setUp(self):
        self.temp = tempfile.TemporaryDirectory()
        self.addCleanup(self.temp.cleanup)
        self.root = Path(self.temp.name)
        (self.root / "PROMPTS").mkdir()
        for test in metrics.TESTS:
            (self.root / "PROMPTS" / (test + ".md")).write_bytes(b"Exact prompt\r\n")
        self.model = "example/model-v1"

    def start(self):
        with patch.object(metrics, "now", return_value="2026-09-24T12:00:00.000Z"):
            return metrics.start(self.root, self.model)

    def artifacts(self):
        directory = metrics.model_dir(self.root, self.model)
        for test in metrics.TESTS:
            folder = directory / test
            folder.mkdir()
            (folder / "output.html").write_text("<!doctype html><title>fixture</title>")
            prompt = (self.root / "PROMPTS" / (test + ".md")).read_bytes()
            (folder / "prompt.md").write_bytes(prompt)
            metrics.write_json(folder / "meta.json", dict(provider="example", model="model-v1",
                test_id=test, prompt_hash="sha256:" + hashlib.sha256(prompt).hexdigest()))

    def finish(self, report=None):
        with patch.object(metrics, "now", return_value="2026-09-24T12:02:03.456Z"):
            return metrics.finish(self.root, self.model, report or usage())

    def test_whole_run_interval_and_generated_index(self):
        self.start()
        self.artifacts()
        run = metrics.read_json(self.finish())
        self.assertEqual(run["duration_ms"], 123456)
        self.assertEqual(run["usage"]["total_tokens"], 200)
        self.assertEqual(run["test_ids"], list(metrics.TESTS))
        # No per-prompt times are summed, regardless of worker overlap.
        index = metrics.index_text(self.root)
        self.assertIn('"duration_ms": 123456', index)
        self.assertEqual(index, metrics.index_text(self.root))

    def test_historical_folders_untouched_and_cannot_backfill(self):
        folder = metrics.model_dir(self.root, self.model)
        folder.mkdir(parents=True)
        old = folder / "meta.json"
        old.write_bytes(b'{"old": true}\r\n')
        before = old.read_bytes()
        with self.assertRaises(FileExistsError):
            self.start()
        self.assertEqual(metrics.index_text(self.root),
            "// Generated by scripts/run_metrics.py build; do not edit.\nwindow.ARENA_RUN_METRICS = {};\n")
        self.assertEqual(old.read_bytes(), before)
        self.assertFalse((folder / "run.json").exists())

    def test_refuses_repeated_finish_without_changing_record(self):
        path = self.start()
        self.artifacts()
        self.finish()
        before = path.read_bytes()
        with self.assertRaisesRegex(ValueError, "no overwrites"):
            self.finish()
        self.assertEqual(before, path.read_bytes())

    def test_rejects_traversal(self):
        for model in ("../evil", "example/..", "a/b/c", "C:/evil", "a\\b", "/tmp/evil"):
            with self.subTest(model=model), self.assertRaises(ValueError):
                metrics.model_dir(self.root, model)

    def test_start_creates_new_provider_directory(self):
        path = metrics.start(self.root, "new-provider/model-v1")
        self.assertTrue(path.is_file())

    def test_malformed_json_object_shapes_fail_as_validation_errors(self):
        with self.assertRaisesRegex(ValueError, "JSON object"):
            metrics.validate_run([], metrics.model_dir(self.root, self.model))
        self.start()
        self.artifacts()
        meta_path = metrics.model_dir(self.root, self.model) / metrics.TESTS[0] / "meta.json"
        meta_path.write_text("[]", encoding="utf-8")
        with self.assertRaisesRegex(ValueError, "metadata must be a JSON object"):
            self.finish()

    def test_missing_artifacts_leave_run_unfinished(self):
        path = self.start()
        with self.assertRaises(ValueError):
            self.finish()
        self.assertEqual(metrics.read_json(path)["status"], "running")

    def test_modified_prompt_or_identity_rejected(self):
        self.start()
        self.artifacts()
        folder = metrics.model_dir(self.root, self.model) / metrics.TESTS[0]
        (folder / "prompt.md").write_bytes(b"Exact prompt\n")
        with self.assertRaisesRegex(ValueError, "canonical bytes"):
            self.finish()
        (folder / "prompt.md").write_bytes(b"Exact prompt\r\n")
        meta = metrics.read_json(folder / "meta.json")
        meta["model"] = "other"
        metrics.write_json(folder / "meta.json", meta)
        with self.assertRaisesRegex(ValueError, "identity|mismatch"):
            self.finish()

    def test_negative_clock_interval_rejected(self):
        path = self.start()
        self.artifacts()
        with patch.object(metrics, "now", return_value="2026-09-24T11:00:00.000Z"):
            with self.assertRaisesRegex(ValueError, "interval"):
                metrics.finish(self.root, self.model, usage())
        self.assertEqual(metrics.read_json(path)["status"], "running")

    def test_partial_and_unavailable_and_real_zero(self):
        reports = [usage(coverage="partial", reason="retry usage absent"),
            usage(coverage="unavailable", source="", reason="harness has no usage",
                  input_tokens=None, output_tokens=None, total_tokens=None),
            usage(input_tokens=0, output_tokens=0, total_tokens=0),
            usage(input_tokens=None, output_tokens=None)]
        for report in reports:
            metrics.validate_usage(report)

    def test_bad_usage_rejected(self):
        reports = [usage(total_tokens=201), usage(input_tokens=-1), usage(total_tokens=True),
            usage(total_tokens=2.5), usage(coverage="complete", total_tokens=None),
            usage(coverage="partial", reason=""), usage(source=""),
            usage(coverage="unavailable", reason="unknown"), usage(total_tokens=float("nan")),
            usage(input_tokens=None, output_tokens=None, total_tokens=2**53)]
        for report in reports:
            with self.subTest(report=report), self.assertRaises(ValueError):
                metrics.validate_usage(report)

    def test_unfinished_run_cannot_publish(self):
        self.start()
        with self.assertRaisesRegex(ValueError, "completed"):
            metrics.index_text(self.root)

    def test_tampered_elapsed_time_rejected(self):
        path = self.start()
        self.artifacts()
        self.finish()
        run = metrics.read_json(path)
        run["duration_ms"] += 1
        with self.assertRaisesRegex(ValueError, "interval"):
            metrics.validate_run(run, path.parent)

    def test_cli_lifecycle_and_stale_index(self):
        scripts = self.root / "scripts"
        scripts.mkdir()
        script = scripts / "run_metrics.py"
        script.write_bytes((REPO / "scripts/run_metrics.py").read_bytes())
        def command(*args):
            return subprocess.run([sys.executable, str(script), *args], capture_output=True, text=True)
        self.assertEqual(command("start", self.model).returncode, 0)
        self.artifacts()
        report = self.root / "usage.json"
        metrics.write_json(report, usage())
        result = command("finish", self.model, "--usage", str(report))
        self.assertEqual(result.returncode, 0, result.stderr)
        self.assertNotEqual(command("check").returncode, 0)
        self.assertEqual(command("build").returncode, 0)
        self.assertEqual(command("check").returncode, 0)
        (self.root / "run-metrics.js").write_text("stale")
        self.assertNotEqual(command("check").returncode, 0)

    def test_cli_unavailable(self):
        self.start()
        self.artifacts()
        scripts = self.root / "scripts"
        scripts.mkdir()
        script = scripts / "run_metrics.py"
        script.write_bytes((REPO / "scripts/run_metrics.py").read_bytes())
        result = subprocess.run([sys.executable, str(script), "finish", self.model,
                                 "--unavailable", "no usage export"], capture_output=True, text=True)
        self.assertEqual(result.returncode, 0, result.stderr)
        run = metrics.read_json(metrics.model_dir(self.root, self.model) / "run.json")
        self.assertIsNone(run["usage"]["total_tokens"])
        self.assertEqual(run["usage"]["coverage"], "unavailable")


if __name__ == "__main__":
    unittest.main()
